# Generated by Django 4.2.15 on 2024-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
